k8s_yaml(kustomize('src/main/k8s/exercise_08/'))

# docker_build('gedoplan-seminar/ctr-exercise-rest', '.')
custom_build('gedoplan-seminar/ctr-exercise-rest', 'mvn package -P docker -Dimagetag=$EXPECTED_REF', ['Dockerfile'], live_update=[sync('./target/ctr-exercise-rest.war', '//opt/jboss/wildfly/standalone/deployments/ctr-exercise-rest.war')])

k8s_resource('exercise', port_forwards=8080)