apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../bases

secretGenerator:
- name: rest-demo-db-secret
  behavior: merge
  env: db-secret.env

patchesStrategicMerge:
- patch-resources.yaml

commonLabels:
  env: dev
