apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-deployment.yaml
- app-ingress.yaml
- app-service.yaml
- app-serviceaccount.yaml
- view-pods-role.yaml
- view-pods-rolemapping.yaml

commonLabels:
  app.kubernetes.io/name: rest-demo
  app.kubernetes.io/component: server
