apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name:  rest-demo
  labels:
    name: rest-demo
spec:
  selector:
    matchLabels:
      name: rest-demo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  rest-demo
    spec:
      containers:
      - image:  gedoplan-seminar/ctr-demo-rest
        name:  rest-demo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort:  8080
          name:  web
  strategy:
    blueGreen:
      activeService: rest-demo
      previewService: rest-demo-preview
      autoPromotionEnabled: false
