apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  rest-demo
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  rest-demo
    spec:
      containers:
      - image:  gedoplan-seminar/ctr-demo-rest
        name:  rest-demo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort:  8080
          name:  web
