apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

bases:
  - github.com/argoproj/argo-rollouts//manifests/cluster-install?ref=v0.4.2


patchesStrategicMerge:
- namespace-patch.yaml
