apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: maven:3.6.1-jdk-11-slim
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /root/.m2/repository
      name: m2
  - name: docker
    image: docker:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker
  - name: kustomize
    image: bitlayer/kustomize:v2.1.0
    command:
    - cat
    tty: true
  - name: git
    image: alpine/git:1.0.7
    command:
    - cat
    tty: true
    volumeMounts:
      - mountPath: /root
        name: git-credentials
  - name: argocd
    image: byrnedo/alpine-curl:0.1.7
    command:
    - cat
    tty: true
    envFrom:
    - secretRef:
        name: argocd-sync
    env:
    # Workaround für argo unter alpine
    - name: USER
      value: argocd
  volumes:
  - name: m2
    persistentVolumeClaim:
      claimName: maven-m2
  - name: docker
    hostPath:
      path: /var/run/docker.sock
  - name: git-credentials
    secret:
      secretName: git-k8s-apps
