apiVersion: v1
kind: Secret
metadata:
  name: git-k8s-apps
type: Opaque
data:
  .git-credentials: aHR0cDovL3Jvb3Q6cm9vdEBnaXRidWNrZXQuaW5mcmE=
stringData:
  .gitconfig: |
    [credential]
    helper = store
    [user]
    email = jenkins@cluster.local
    name = jenkins
