apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kustomize
    image: bitlayer/kustomize:v2.1.0
    command:
    - cat
    tty: true
  - name: git
    image: alpine/git:1.0.7
    command:
    - cat
    tty: true
    volumeMounts:
      - mountPath: /root
        name: git-credentials
  - name: argocd
    image: byrnedo/alpine-curl:0.1.7
    command:
    - cat
    tty: true
    envFrom:
    - secretRef:
        name: argocd-sync
    env:
    # Workaround für argo unter alpine
    - name: USER
      value: argocd
  volumes:
  - name: git-credentials
    secret:
      secretName: git-k8s-apps
