apiVersion: apps/v1
kind: Deployment
metadata:
  name:  rest-demo
spec:
  template:
    spec:
      containers:
      - name:  rest-demo
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
