apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rest-demo
spec:
  rules:
  - host: rest-demo.localtest.me
    http:
      paths:
      - path: /
        backend:
          serviceName: rest-demo
          servicePort: web
