apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: maven:3.6.1-jdk-11-slim
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /root/.m2/repository
      name: m2
  volumes:
  - name: m2
    persistentVolumeClaim:
      claimName: maven-m2
