kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-exercise-pods-rolebinding
subjects:
- kind: ServiceAccount
  name: exercise
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-exercise-pods-role
