apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-db
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: exercise-db
  template:
    metadata:
      labels:
        name: exercise-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.3
        ports:
        - containerPort: 3306
          name: db
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: exercise-db
                key: rootpassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: exercise-db
                key: database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: exercise-db
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: exercise-db
                key: password
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: db-volume
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: exercise-db
